spring.data.web.pageable.one-indexed-parameters: true

server:
  port: 8080
  
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;
    username: sa 
  jpa:
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      javax.persistence.validation.mode: none
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      validator.apply_to_ddl: false
      ddl-auto: create
